# Generated by Django 5.2.15 on 2026-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_date_taken_photo_latitude_photo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
