# Generated by Django 5.2.15 on 2026-06-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='longitude',
        ),
    ]
