# Generated by Django 5.2.15 on 2026-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_photo_latitude_remove_photo_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to='medium/'),
        ),
    ]
