# Generated by Django 5.2.15 on 2026-07-12 00:17

import django.db.models.deletion
from django.db import migrations, models


def set_default_covers(apps, schema_editor):
    Album = apps.get_model("gallery", "Album")
    for album in Album.objects.all():
        latest = (
            album.photoalbum_set.select_related("photo")
            .order_by("-photo__uploaded_at")
            .first()
        )
        if latest:
            album.cover_photo = latest.photo
            album.save(update_fields=["cover_photo"])


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_album_photoalbum_album_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_of', to='gallery.photo'),
        ),
        migrations.RunPython(set_default_covers, migrations.RunPython.noop),
    ]
